version: "3.8"

services:
    # The Modbus TCP Server is a simple, in python written, Modbus TCP server. 
    # It listens to port 5020 and respond to any register types with a 0x0000. 
    # The Modbus registers can be also predefined with values.
    modbus_server:
        container_name: modbus_server
        image: oitc/modbus-server
        restart: always
        command: -f /server_config.json
        volumes:
            - ./modbus/server_config.json:/server_config.json
        ports:
            - target: 5020 # the port inside the container
              published: 5020 # the publicly exposed port
              protocol: tcp
              mode: bridge

    glide_away_api:
        container_name: glide_away_api
        build: 
            context: ./api
            dockerfile: Dockerfile
        ports:
            - target: 3001
              published: 3001
              protocol: tcp
              mode: bridge

    glide_away_app:
        container_name: glide_away_app
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
              mode: bridge

    glide_away_stream:
        container_name: glide_away_stream
        build:
            context: ./stream
            dockerfile: Dockerfile